[tool.poetry]
name = "cfgimp"
version = "0.1.0"
description = "An intelligent importlib-compatible Python loader which allows for static importing of data"
license = "MIT"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
